### ISSUE TITLE
How to compute 2D and 3D landmarks

### ISSUE THREAD

**Issue by eigenvivek** [rg2/DeepFluoroLabeling-IPCAI2020#4]
Hi Robert, I am curious how the locations for the 3D `vol-landmarks` the 2D `gt-landmarks` are generated. Are these values in the CTs / fluoroscopy images that we can identify by pixel intensity?

**Comment by rg2** [comment]
The 3D landmarks are manually annotated. I used 3D Slicer to pick points on the 3D surfaces of the bones (meshes created from segmentation). Center of the femoral head landmarks required some additional adjustment in the CT slices.

The 2D landmarks are obtained by projecting the 3D landmarks into 2D using the corresponding ground truth transformation.

**Comment by rg2** [comment]
There is no specific pixel intensity used to directly identify a landmark.

Except for the center of the femoral head, these landmarks are fairly easy to pick out in 3D by looking at the curvature of the bone surface. Center of the femoral head can be adjusted in multiple CT planes (e.g. axial and coronal) so that the landmark is approximately in the center.

**Comment by eigenvivek** [comment]
Thank you for the information! I see I had a misconception - I thought the ground truth transformation was solved for using the 2D/3D landmarks. Is the ground truth pose instead encoded in the original image file (e.g., in the DICOM)?

**Comment by rg2** [comment]
The ground truth transformations are stored in the hdf5 files. This page describes their layout/structure: hdf5_layouts/Readme.md

The code used to calculate ground the ground truth transforms is here: https://github.com/rg2/Regi2D3D-IPCAI2020

**Comment by eigenvivek** [comment]
Ah, I see! Thank you very much for pointing me to the Regi2D3D repo, that answers all my questions.

**Comment by rg2** [comment]
You're welcome!
