### ISSUE TITLE
Intrinsic matrix

### ISSUE THREAD

**Issue by pimatysiak** [rg2/DeepFluoroLabeling-IPCAI2020#5]
Hi Robert, thank you for this code and especially dataset, it's incredibly thorough and very useful!

However I have one question, how do you generate the "intrinsic" matrix found in the "proj-params" section of the dataset? From what I understand, you can obtain the extrinsic matrix using information provided with most CT files, however I have not found how to extract or simulate the intrinsic matrix using a different set of data. Is that directly related to the specific C-arm or capture device? Would one be able to get this information just from a DICOM series? I understand this may not be your expertise but if you had an insight on that it'd be greatly appreciated.

**Comment by rg2** [comment]
Hi @pimatysiak , thanks a lot for your question.

For this dataset, I did use fields in the original DICOM. Specifically, the image pixel spacings and the source-to-detector length. I made an assumption that the principal point lies at the center of the detector/image.

In reality, the principal point will lie someplace else, and moreover, will change depending on the orbital rotation of the C-arm (the source-to-detector length will also change). However, approximate intrinsics often work good enough for registration purposes, especially when you are interested in the relative pose of two objects in the X-ray view.

When the metadata is not present in the DICOM or not available via some other source, you need to run a calibration to estimate the intrinsics. This could be done with a specific calibration phantom or you could treat patient anatomy with a known 3D shape as the phantom.

I have an example of estimating intrinsics from DICOM metadata here: https://github.com/rg2/xreg/blob/master/lib/file_formats/xregReadProjDataFromDICOMDetail.h in the `ReadProjDataFromDICOMHelper` function.

I extract DICOM metadata here: https://github.com/rg2/xreg/blob/master/lib/file_formats/xregDICOMUtils.cpp#L41 in the `ReadDICOMFileBasicFields` function. I use the gdcm library which is bundled with ITK, but you can use your preferred dicom library.

Hope that helps!

**Comment by pimatysiak** [comment]
Thanks a lot for your answer!

It's good to know you can approximate these intrinsics to an acceptable working level. I'll also look into this calibration process because indeed a good amount of my data doesn't have what I would need.

**Comment by pimatysiak** [comment]
Thanks a lot for your answer!

It's good to know you can approximate these intrinsics to an acceptable working level. I'll also look into this calibration process because indeed a good amount of my data doesn't have what I would need.

**Comment by pimatysiak** [comment]
Hi Robert,

Sorry to bother you again but I wanted to confirm I use the proper values. So if in my DICOM files I have a "DistanceSourceToDetector" value of 1085.6 and "PixelSpacing" values of 0.96 my intrinsic matrix should ressemble something like this:

[1085.6    0.              0.96
 0.            1085.6      0.96
 0.            0.              1.]
 
Are these the correct tags to use? I only want to double-check with you because the values for the intrinsic matrix in your dataset are quite different (notably negative values for the first 2 columns).

**Comment by rg2** [comment]
Those dicom tags should work. The negative values pop up depending on how your z-axis is oriented, towards detector or away from it.
