### ISSUE TITLE
how to get the parameter? (cam-to-pelvis-vol)

### ISSUE THREAD

**Issue by ryukyungjoon** [rg2/DeepFluoroLabeling-IPCAI2020#7]
Hello. I am trying to create a custom dataset following the format of ipcai_2020_full_res_data.h5. I want to obtain the cam-to-pelvis-vol parameter, but I am having difficulty understanding its meaning.

Initially, I thought it was the transformation matrix from the source to the volume when generating DRRs. However, upon examining the data, I found that the values differ internally for different regions even for a single DRR.

What does this parameter mean? And how can I obtain it? I would appreciate it if you could explain. Thank you.

**Comment by rg2** [comment]
It is the rigid transformation mapping the pelvis object in CT coordinates into the X-ray "camera" extrinsic frame. Each projection also has metadata describing the rigid mapping from extrinsic frame to the projective frame, and also the projection mapping from projective frame to 2D pixels.
